// news.js — FREECHECK0X_20260928：安全快讯案例库（构思 v3 附录三，66 条，每一条都打开过来源核对；DSJ 09-28「构思定稿：定了」）。
//   中文照附录三原文；英文是同一句的翻译，不多一个数字、不少一个限定（「未注明」「未披露」照写）。
//   顶部细条、首页三张新闻卡、查询结果下面那一条、「全部快讯」都从这里取。纯数据，不联网。
//   c = 类别（poison 投毒 · key 私钥 · fake 假币 · site 假网址 / 冒充 · scale 整体规模）· d = 日期 · ch = 链 · a = 金额 · w = 发生了什么 · l = 教训 · s = 来源
var NEWS = [
  { c: 'poison', d: ['2024-05-03', '2024-05-03'], ch: ['以太坊', 'Ethereum'], a: ['1,155 WBTC（约 6,800 万美元，后退回）', '1,155 WBTC (about $68M, later returned)'],
    w: ['假地址头 4 位、尾 6 位跟真的一样，受害人复制错', 'The fake address matched the first 4 and last 6 characters of the real one, and the victim copied the fake'],
    l: ['头尾一样不等于同一个地址', 'Same start and end does not mean the same address'],
    s: [['SlowMist', 'https://slowmist.medium.com/small-bait-big-fish-unveiling-the-1155-wbtc-phishing-incident-22bf53b6fe60'], ['Cointelegraph', 'https://cointelegraph.com/news/wbtc-address-poisoner-all-funds-negotiations']] },
  { c: 'poison', d: ['2024-11', '2024-11'], ch: ['波场', 'TRON'], a: ['1.29 亿 USDT（后全数退回）', '129 million USDT (later returned in full)'],
    w: ['假地址 THc…bu8 冒充 TMS…bu8：开头除了 T 全不一样，结尾都是 bu8', 'Fake address THc…bu8 posed as TMS…bu8: apart from the T the beginnings are completely different; both end in bu8'],
    l: ['波场地址都以 T 开头，只对首尾几位等于没对', 'Every TRON address starts with T - checking only a few characters at each end is no check at all'],
    s: [['CryptoSlate', 'https://cryptoslate.com/crypto-phishing-scam-nets-129-million-in-usdt-then-funds-mysteriously-return/']] },
  { c: 'poison', d: ['2025-04（报道）', '2025-04 (reported)'], ch: ['比特币', 'Bitcoin'], a: ['一例 0.1 BTC', 'one case: 0.1 BTC'],
    w: ['Casa 的 Lopp 扫了整条比特币链，2023 年以来约 4.8 万次疑似投毒', 'Casa\'s Jameson Lopp scanned the whole Bitcoin chain: about 48,000 suspected poisoning attempts since 2023'],
    l: ['投毒不只针对 USDT', 'Poisoning is not only about USDT'],
    s: [['The Block', 'https://www.theblock.co/post/349736/bitcoin-address-poisoning-attacks-on-the-rise-warns-casa-cso-jameson-lopp']] },
  { c: 'poison', d: ['2025-05（报道）', '2025-05 (reported)'], ch: ['未注明', 'Not stated'], a: ['约 260 万美元 USDT', 'about $2.6M in USDT'],
    w: ['同一个投毒地址，3 小时内骗了同一个人两次', 'The same poisoning address fooled the same person twice within 3 hours'],
    l: ['转错一次后，假地址还留在记录里', 'After one mistake, the fake address is still sitting in your history'],
    s: [['CCN', 'https://www.ccn.com/news/crypto/victim-loses-2-6m-usdt-scamaddress-poisoning-trap-twice/']] },
  { c: 'poison', d: ['2025-12-20', '2025-12-20'], ch: ['以太坊', 'Ethereum'], a: ['49,999,950 USDT', '49,999,950 USDT'],
    w: ['先转 50 USDT 测试，骗子随后塞进假地址；测试后 26 分钟复制错；悬赏 100 万美元', 'A 50 USDT test went first; the scammer then planted a fake address; 26 minutes after the test the victim copied the fake; a $1M bounty was offered'],
    l: ['测试成功，只说明地址能收钱', 'A successful test only proves the address can receive money'],
    s: [['The Block', 'https://www.theblock.co/post/383423/crypto-trader-loses-50-million-in-address-poisoning-attack-offers-1-million-bounty-for-return']] },
  { c: 'poison', d: ['2026-01-16', '2026-01-16'], ch: ['以太坊', 'Ethereum'], a: ['51.4 万 USDT', '514,000 USDT'],
    w: ['5,000 USDT 的「测试」其实已经转进了假地址，2 分钟后又转了 50.9 万', 'The 5,000 USDT "test" had already gone to the fake address; 2 minutes later another 509,000 followed'],
    l: ['小额测试不能代替核对整串地址', 'A small test does not replace checking the whole address'],
    s: [['Cryptopolitan', 'https://www.cryptopolitan.com/address-poison-scam-victim-loses-500k/']] },
  { c: 'poison', d: ['2026 年 1 月底', 'late January 2026'], ch: ['以太坊', 'Ethereum'], a: ['4,556 ETH（约 1,240 万美元）', '4,556 ETH (about $12.4M)'],
    w: ['骗子盯了两个月，仿的是他做场外交易结算用的入金地址；32 小时前打了一笔零头', 'The scammer watched for two months and imitated the deposit address he used to settle OTC trades; the dust landed 32 hours before'],
    l: ['骗子会先盯你的记录，专挑你付大钱的地址来仿', 'Scammers study your history first and imitate the address you send big amounts to'],
    s: [['BeInCrypto', 'https://beincrypto.com/ethereum-holder-address-poisoning-attack/']] },
  { c: 'poison', d: ['2026-02（报道）', '2026-02 (reported)'], ch: ['以太坊', 'Ethereum'], a: ['约 26.4 万美元（3.5 WBTC）', 'about $264K (3.5 WBTC)'],
    w: ['骗子借 Phantom 钱包的聊天功能塞假地址，受害人从记录里复制', 'The scammer planted a fake address through the Phantom wallet\'s chat feature; the victim copied it from the history'],
    l: ['聊天记录跟转账记录一样会被塞假地址', 'Chat history can be poisoned just like transfer history'],
    s: [['Cointelegraph', 'https://cointelegraph.com/news/phantom-chat-address-poisoning-bitcoin-phishing']] },
  { c: 'poison', d: ['2026-02-17', '2026-02-17'], ch: ['未注明', 'Not stated'], a: ['约 60 万美元', 'about $600K'],
    w: ['骗子用 0 元转账把假地址塞进记录，受害人从记录里复制错（Cyvers 发现）', 'A zero-value transfer planted the fake address in the history, and the victim copied it from there (spotted by Cyvers)'],
    l: ['从转账记录里复制地址，最容易中招', 'Copying an address from your transfer history is exactly where people get caught'],
    s: [['Cryptopolitan', 'https://www.cryptopolitan.com/victim-loses-600k-address-poisoning-attacks/']] },
  { c: 'poison', d: ['2026-03', '2026-03'], ch: ['TON', 'TON'], a: ['12.6 万 TON（约 22 万美元，后退回大部分）', '126,000 TON (about $220K, most of it later returned)'],
    w: ['大户从最近的记录里复制了常用收款方的「相似地址」', 'A large holder copied a look-alike of a regular payee from recent history'],
    l: ['TON 链一样有投毒', 'TON gets poisoned too'],
    s: [['CCN', 'https://www.ccn.com/education/crypto/ton-whale-loses-220k-address-poisoning-scam-returns-203k/']] },
  { c: 'poison', d: ['2026-08（报道）', '2026-08 (reported)'], ch: ['未注明', 'Not stated'], a: ['约 10 万 USDT', 'about 100,000 USDT'],
    w: ['假地址 66 天前就埋进了受害人的记录', 'The fake address had been planted in the victim\'s history 66 days earlier'],
    l: ['老记录也不能直接复制', 'Old records are not safe to copy either'],
    s: [['crypto.news', 'https://crypto.news/address-poisoning-attack-drains-100k-dollars-usdt/']] },
  { c: 'poison', d: ['2026-08', '2026-08'], ch: ['波场', 'TRON'], a: ['940 万美元', '$9.4M'],
    w: ['同一个团伙四周内投毒 15 人', 'One gang poisoned 15 people in four weeks'],
    l: ['波场是投毒重灾区', 'TRON is a poisoning hotspot'],
    s: [['CryptoRank', 'https://cryptorank.io/news/feed/00d9b-tron-users-address-poisoning-wallet-defense']] },
  { c: 'poison', d: ['2026-08-21', '2026-08-21'], ch: ['以太坊', 'Ethereum'], a: ['200 万美元 USDC', '$2M in USDC'],
    w: ['Bofur Capital：40 位地址只对上 7 位（头 4、尾 3）', 'Bofur Capital: of the 40 characters only 7 matched (first 4, last 3)'],
    l: ['只对头尾几位不够', 'Checking a few characters at each end is not enough'],
    s: [['CryptoTimes', 'https://www.cryptotimes.io/2026/08/22/bofur-capital-drained-of-2m-minutes-after-compound-withdrawal/'], ['CryptoTicker', 'https://cryptoticker.io/en/address-poisoning-check-wallet-address/']] },

  { c: 'key', d: ['2022-09', '2022-09'], ch: ['以太坊', 'Ethereum'], a: ['1.6 亿美元', '$160M'],
    w: ['做市商 Wintermute 的管理员靓号地址用 Profanity 生成，私钥被反推', 'Market maker Wintermute\'s admin vanity address was generated with Profanity, and its private key was worked out backwards'],
    l: ['靓号怎么生成的，决定它安不安全', 'How a vanity address was generated decides whether it is safe'],
    s: [['The Block', 'https://www.theblock.co/post/171192/experts-blame-a-vanity-address-bug-for-wintermutes-160-million-hack']] },
  { c: 'key', d: ['2022-09', '2022-09'], ch: ['以太坊', 'Ethereum'], a: ['330 万美元', '$3.3M'],
    w: ['同一个漏洞，一批 Profanity 靓号地址被盗', 'The same flaw: a batch of Profanity vanity addresses was drained'],
    l: ['靓号怎么生成的，决定它安不安全', 'How a vanity address was generated decides whether it is safe'],
    s: [['The Block', 'https://www.theblock.co/post/170971/hacker-stole-3-3-million-from-ethereum-vanity-addresses-created-with-profanity-tool']] },
  { c: 'key', d: ['2022-09', '2022-09'], ch: ['以太坊', 'Ethereum'], a: ['约 95 万美元', 'about $950K'],
    w: ['同一个漏洞，又一批', 'The same flaw, another batch'],
    l: ['靓号怎么生成的，决定它安不安全', 'How a vanity address was generated decides whether it is safe'],
    s: [['Cointelegraph', 'https://cointelegraph.com/news/almost-1m-in-crypto-stolen-from-vanity-address-exploit']] },
  { c: 'key', d: ['未注明', 'Not stated'], ch: ['多链', 'Multi-chain'], a: ['—', '—'],
    w: ['Multicall3 的部署钥匙用 Profanity 生成后泄露，攻击者在 Ancient8 链上占了它的地址', 'Multicall3\'s deployer key was generated with Profanity and leaked; an attacker took its address on the Ancient8 chain'],
    l: ['合约靓号用「算盐」，就没有钥匙可泄露', 'A contract vanity address made by computing a salt has no key to leak'],
    s: [['mds1/multicall3', 'https://github.com/mds1/multicall3']] },
  { c: 'key', d: ['2024-07（第 28 期）', '2024-07 (issue 28)'], ch: ['以太坊', 'Ethereum'], a: ['—', '—'],
    w: ['有人卖「66666」这类靓号，自己留着私钥，买家转钱进去几天后被转走', 'Someone sold vanity addresses like "66666" but kept the private keys; buyers\' funds were taken a few days after they deposited'],
    l: ['买来的靓号，私钥经过了别人的手', 'The private key of a vanity address you buy has passed through someone else\'s hands'],
    s: [['imToken 安全月报第 28 期 / imToken Security Monthly #28', 'https://support.token.im/hc/en-us/articles/35264238839449-Vanity-Wallet-Address-Scam-Security-Monthly-Report-28th-Issue']] },
  { c: 'key', d: ['2025-02-05（披露）', '2025-02-05 (disclosed)'], ch: ['手机', 'Phones'], a: ['未披露', 'Not disclosed'],
    w: ['SparkCat 木马混进 App Store 和 Google Play，扫相册里的助记词截图', 'The SparkCat trojan got into the App Store and Google Play and scanned photo albums for screenshots of recovery phrases'],
    l: ['助记词不要截图', 'Never screenshot your recovery phrase'],
    s: [['Kaspersky', 'https://www.kaspersky.com/about/press-releases/kaspersky-discovers-new-crypto-stealing-trojan-in-appstore-and-google-play']] },
  { c: 'key', d: ['2025-02-24（披露）', '2025-02-24 (disclosed)'], ch: ['比特币', 'Bitcoin'], a: ['约 5 BTC', 'about 5 BTC'],
    w: ['GitHub 上几百个假开源项目带着「换地址」木马，你复制的地址会被换成黑客的', 'Hundreds of fake open-source projects on GitHub carried an address-swapping trojan: the address you copy is replaced with the attacker\'s'],
    l: ['粘贴之后要再对一遍', 'Check again after you paste'],
    s: [['Kaspersky', 'https://www.kaspersky.com/about/press-releases/kaspersky-exposes-hidden-malware-on-github-stealing-personal-data-and-485000-in-bitcoin']] },
  { c: 'key', d: ['2025-03-11（披露）', '2025-03-11 (disclosed)'], ch: ['多链', 'Multi-chain'], a: ['约 9.5 万美元', 'about $95K'],
    w: ['MassJacker 藏在盗版软件里，一看到剪贴板里有地址就替换，背后备了 77 万多个收款地址', 'MassJacker hid in pirated software and replaced any address it saw in the clipboard, backed by more than 770,000 receiving addresses'],
    l: ['装盗版软件，等于给剪贴板装了窃听器', 'Installing pirated software is like bugging your own clipboard'],
    s: [['BleepingComputer', 'https://www.bleepingcomputer.com/news/security/massjacker-malware-uses-778-000-wallets-to-steal-cryptocurrency/']] },
  { c: 'key', d: ['2025-06-06（披露）', '2025-06-06 (disclosed)'], ch: ['多链', 'Multi-chain'], a: ['未披露', 'Not disclosed'],
    w: ['Google Play 上 20 多个假 App 冒充 PancakeSwap、Hyperliquid 等骗助记词', 'More than 20 fake apps on Google Play posed as PancakeSwap, Hyperliquid and others to steal recovery phrases'],
    l: ['商店里搜得到，不等于是官方的', 'Being in the app store does not make it official'],
    s: [['Cyble', 'https://cyble.com/blog/crypto-phishing-applications-on-the-play-store/']] },
  { c: 'key', d: ['2025-09-08', '2025-09-08'], ch: ['多链', 'Multi-chain'], a: ['约 600 美元（很快被发现）', 'about $600 (caught quickly)'],
    w: ['每周下载 20 亿次的 npm 包被植入代码，在网页里把收款地址换成「长得最像」的黑客地址', 'npm packages downloaded 2 billion times a week were injected with code that swapped the payee address on web pages for the attacker\'s closest look-alike'],
    l: ['网页本身也会被下毒，签名前逐字核对', 'Web pages themselves can be poisoned - check every character before you sign'],
    s: [['The Hacker News', 'https://thehackernews.com/2025/09/20-popular-npm-packages-with-2-billion.html']] },
  { c: 'key', d: ['2025-12-24', '2025-12-24'], ch: ['多链', 'Multi-chain'], a: ['约 700 万美元', 'about $7M'],
    w: ['Trust Wallet 官方浏览器插件被推送了恶意版本，2,596 个钱包被清空', 'A malicious version of Trust Wallet\'s official browser extension was pushed out; 2,596 wallets were emptied'],
    l: ['官方插件也会出事，大钱别放浏览器插件', 'Official extensions can go wrong too - keep large amounts out of browser extensions'],
    s: [['BleepingComputer', 'https://www.bleepingcomputer.com/news/security/trust-wallet-says-7-million-crypto-theft-attack-drained-2-596-wallets/']] },
  { c: 'key', d: ['2026-05（披露）', '2026-05 (disclosed)'], ch: ['波场', 'TRON'], a: ['未披露', 'Not disclosed'],
    w: ['Chrome 商店里的假 TronLink 插件，借用「100 万+ 用户、4.5 星」的老页面偷助记词', 'A fake TronLink extension in the Chrome store reused an old listing with "1M+ users, 4.5 stars" to steal recovery phrases'],
    l: ['评分和用户数可以是借来的', 'Ratings and user counts can be borrowed'],
    s: [['慢雾 / SlowMist', 'https://slowmist.medium.com/threat-intelligence-analysis-of-a-fake-tronlink-chrome-extension-phishing-campaign-768e8c0e8fb6']] },
  { c: 'key', d: ['2026-06（报道）', '2026-06 (reported)'], ch: ['Cardano', 'Cardano'], a: ['约 240 万美元', 'about $2.4M'],
    w: ['SecondFi 钱包自己的生成程序有缺陷，374 个钱包被清空', 'A flaw in the SecondFi wallet\'s own key generator let 374 wallets be emptied'],
    l: ['生成程序有问题，私钥就不只你知道', 'If the generator is flawed, you are not the only one who knows your key'],
    s: [['CoinDesk', 'https://www.coindesk.com/business/2026/06/24/secondfi-loses-usd2-4-million-in-cardano-wallet-exploit-with-up-to-usd20-million-at-risk']] },
  { c: 'key', d: ['2026-07-30', '2026-07-30'], ch: ['比特币', 'Bitcoin'], a: ['约 1,816 BTC（约 1.16 亿美元）', 'about 1,816 BTC (about $116M)'],
    w: ['Coldcard Mk3 旧固件跳过了硬件随机数，私钥被批量算出', 'Old Coldcard Mk3 firmware skipped the hardware random number generator, so private keys could be computed in bulk'],
    l: ['随机数不够随机，私钥就能被算出来（跟 Profanity 同一类）', 'If the randomness is not random, the key can be computed (the same class of problem as Profanity)'],
    s: [['CoinDesk', 'https://www.coindesk.com/tech/2026/07/31/major-bitcoin-wallet-flaw-drains-594-btc-in-25-minute-sweep'], ['TRM', 'https://www.trmlabs.com/resources/blog/the-largest-hardware-wallet-exploit-of-2026-inside-the-usd-116-million-coldcard-hack']] },
  { c: 'key', d: ['2026-09-09～17', '2026-09-09 to 17'], ch: ['多链', 'Multi-chain'], a: ['约 58 万 USDT', 'about 580,000 USDT'],
    w: ['自称「只读」的 App Store 应用 FomoPeek 暗中偷 19 个钱包 App 的私钥和助记词', 'FomoPeek, an App Store app that claimed to be "read-only", secretly stole private keys and recovery phrases from 19 wallet apps'],
    l: ['说自己「不碰私钥」的 App 也可能偷', 'An app that says it "never touches keys" can still steal them'],
    s: [['慢雾 / SlowMist', 'https://slowmist.medium.com/threat-intelligence-analysis-of-fomopeek-app-store-poisoning-and-ios-kernel-exploitation-e568762d11ca']] },

  { c: 'fake', d: ['2023-08-07 起', 'from 2023-08-07'], ch: ['多链', 'Multi-chain'], a: ['最大一个成交约 260 万美元', 'the largest traded about $2.6M'],
    w: ['PayPal 宣布 PYUSD 后一天之内，冒出近 30 个假 PYUSD 交易对', 'Within a day of PayPal announcing PYUSD, nearly 30 fake PYUSD trading pairs appeared'],
    l: ['真币刚发时假币最多', 'Fakes peak right when a real token launches'],
    s: [['Cointelegraph', 'https://cointelegraph.com/news/paypal-stablecoin-launch-sparks-fake-pyusd-tokens']] },
  { c: 'fake', d: ['2024-08-21', '2024-08-21'], ch: ['Solana', 'Solana'], a: ['黑客自称赚了 70 万美元', 'the hackers claimed $700K'],
    w: ['麦当劳 Instagram 被盗，推假 GRIMACE 币', 'McDonald\'s Instagram was hijacked to push a fake GRIMACE token'],
    l: ['大品牌官号发币，先去官网核实', 'When a big brand\'s account announces a token, check its official website first'],
    s: [['Decrypt', 'https://decrypt.co/245783/mcrugged-hackers-mcdonalds-instagram-make-700k-grimace-token']] },
  { c: 'fake', d: ['2025-01-17/18', '2025-01-17/18'], ch: ['多链', 'Multi-chain'], a: ['—', '—'],
    w: ['TRUMP 上线那个周末，带 Trump 名字的代币涨到 6,800 个，24 小时 91 个假网站', 'The weekend TRUMP launched, tokens with Trump in the name grew to 6,800, with 91 fake websites in 24 hours'],
    l: ['名字一样不等于同一个币', 'The same name is not the same token'],
    s: [['crypto.news（引 Blockaid）/ crypto.news (citing Blockaid)', 'https://crypto.news/scammers-deployed-6800-fake-tokens-amid-trump-meme-coin-craze-blockaid/']] },
  { c: 'fake', d: ['2025-01-22', '2025-01-22'], ch: ['Solana', 'Solana'], a: ['市值冲到 8,000 万美元后归零', 'market value hit $80M, then went to zero'],
    w: ['纳斯达克官方 X 被盗，转发假 STONKS 币', 'Nasdaq\'s official X account was hijacked and promoted a fake STONKS token'],
    l: ['只认合约地址', 'Trust only the contract address'],
    s: [['The Block', 'https://www.theblock.co/news/regulation/2025-01-22-nasdaqs-official-x-account-was-seemingly-hacked-to-promote-a-fake-memecoin-336489']] },
  { c: 'fake', d: ['2025-02-17', '2025-02-17'], ch: ['Solana', 'Solana'], a: ['约 17 万美元（很快跌到约 6.2 万）', 'about $170K (soon worth about $62K)'],
    w: ['知名交易员 Dave Portnoy 误买假 LIBRA 币', 'Well-known trader Dave Portnoy bought a fake LIBRA token by mistake'],
    l: ['老手也会认错币', 'Even veterans pick the wrong token'],
    s: [['The Block', 'https://www.theblock.co/news/business/2025-02-17-dave-portnoy-mistakenly-pumps-random-libra-token-memecoin-trader-poised-to-lose-big-341358']] },
  { c: 'fake', d: ['2025-02-26', '2025-02-26'], ch: ['Solana', 'Solana'], a: ['假币市值冲到 500 万美元后崩盘', 'the fake reached $5M in market value, then crashed'],
    w: ['Pump.fun 官方 X 被盗，发布假「PUMP」代币', 'Pump.fun\'s official X account was hijacked to launch a fake "PUMP" token'],
    l: ['「官方代币」突然在社交账号首发，先当假的看', 'Treat an "official token" suddenly launched on social media as fake until proven otherwise'],
    s: [['BleepingComputer', 'https://www.bleepingcomputer.com/news/security/pumpfun-x-account-hacked-to-promote-scam-governance-token/']] },
  { c: 'fake', d: ['2025-08（报道）', '2025-08 (reported)'], ch: ['Solana', 'Solana'], a: ['假币估值 700 万美元后跌到 8.2 万', 'the fake was valued at $7M, then fell to $82K'],
    w: ['Kanye West 的 Instagram 被盗，推假 YZY 币', 'Kanye West\'s Instagram was hijacked to push a fake YZY token'],
    l: ['真币刚发时仿冒最多', 'Imitations peak when a real token launches'],
    s: [['Crypto Briefing', 'https://cryptobriefing.com/kanye-west-instagram-hack-yzy-memecoin/']] },
  { c: 'fake', d: ['2026-03-19', '2026-03-19'], ch: ['波场', 'TRON'], a: ['未披露', 'Not disclosed'],
    w: ['冒充 FBI 的 TRC-20 代币被空投进钱包，以「涉嫌洗钱、要冻结你的资产」相威胁，骗人去网站交个人信息', 'TRC-20 tokens posing as the FBI were airdropped into wallets, threatening "suspected money laundering - your assets will be frozen" to lure people into handing over personal details on a website'],
    l: ['莫名到账的代币别点，也别去它给的网站', 'Do not touch tokens that show up out of nowhere, and do not visit the sites they point to'],
    s: [['The Block', 'https://www.theblock.co/post/394441/fbi-warns-fake-tokens-impersonating-agency-tron-network']] },
  { c: 'fake', d: ['2026-03-26（发布）', '2026-03-26 (published)'], ch: ['多链', 'Multi-chain'], a: ['5.4 万多个假稳定币', 'more than 54,000 fake stablecoins'],
    w: ['Blockaid：冒充 USDT 的 3.4 万多个、USDC 约 1.2 万个', 'Blockaid: more than 34,000 imitate USDT and about 12,000 imitate USDC'],
    l: ['钱包里显示「USDT」不代表是真 USDT', '"USDT" in your wallet is not proof that it is real USDT'],
    s: [['Blockaid', 'https://www.blockaid.io/blog/stablecoin-impersonation-threats-expanding-across-malicious-tokens-and-dapps']] },
  { c: 'fake', d: ['2026-05（报道）', '2026-05 (reported)'], ch: ['Solana', 'Solana'], a: ['未披露', 'Not disclosed'],
    w: ['假 Jupiter 代币直接空投进钱包，谁去「领取」就被带到盗币网站', 'Fake Jupiter tokens were airdropped straight into wallets; anyone who tried to "claim" was sent to a draining site'],
    l: ['自己掉进钱包的代币就是鱼饵', 'Tokens that land in your wallet on their own are bait'],
    s: [['Cryptopolitan', 'https://www.cryptopolitan.com/fake-jupiter-aidrop-jupuary-wallet-drainer/']] },
  { c: 'fake', d: ['2026-06（第 49 期）', '2026-06 (issue 49)'], ch: ['波场', 'TRON'], a: ['—', '—'],
    w: ['骗子借交易所热钱包转出假币，冒充真 USDT', 'Scammers moved fake tokens through an exchange hot wallet to pass them off as real USDT'],
    l: ['交易所热钱包的标签不是背书', 'An exchange hot-wallet label is not an endorsement'],
    s: [['imToken 安全月报第 49 期 / imToken Security Monthly #49', 'https://support.token.im/hc/en-us/articles/59274708455193-Beware-of-Fake-USDT-An-Exchange-Hot-Wallet-Label-Is-Not-an-Endorsement-Security-Monthly-Report-49th-Issue']] },

  { c: 'site', d: ['2013-10～2023-12', '2013-10 to 2023-12'], ch: ['—', '—'], a: ['报案涉及约 555 亿美元', 'about $55.5B in reported losses'],
    w: ['FBI：冒充熟人、叫你「把钱改付到另一个账户」的商业邮件诈骗', 'FBI: business email compromise - impostors who ask you to "pay into a different account"'],
    l: ['「我换收款账户了」是骗子最典型的一句', '"I have changed my payment account" is the classic scammer line'],
    s: [['FBI 网络犯罪中心 / FBI IC3', 'https://www.ic3.gov/PSA/2024/PSA240911']] },
  { c: 'site', d: ['2018-02（披露）', '2018-02 (disclosed)'], ch: ['比特币', 'Bitcoin'], a: ['3 年约 5,000 万美元', 'about $50M over 3 years'],
    w: ['Coinhoarder 团伙买 Google 广告，配上拼错的 blockchain.info 网址钓鱼（Cisco Talos 披露）', 'The Coinhoarder gang bought Google ads pointing to misspelled blockchain.info addresses (disclosed by Cisco Talos)'],
    l: ['搜索结果最上面的「官网」，可能是花钱买的假网站', 'The "official site" at the top of search results may be a paid-for fake'],
    s: [['BleepingComputer', 'https://www.bleepingcomputer.com/news/security/group-makes-50-million-by-phishing-bitcoin-users-using-google-adwords/']] },
  { c: 'site', d: ['2024-01（披露）', '2024-01 (disclosed)'], ch: ['多链', 'Multi-chain'], a: ['超过 8,000 万美元', 'more than $80M'],
    w: ['Inferno Drainer 一年里用 1.6 万多个钓鱼域名，冒充 100 多个加密品牌', 'Inferno Drainer used more than 16,000 phishing domains in a year, impersonating over 100 crypto brands'],
    l: ['一个团伙就能造出上万个假官网', 'One gang can create tens of thousands of fake official sites'],
    s: [['Group-IB', 'https://www.group-ib.com/media-center/press-releases/inferno-drainer/']] },
  { c: 'site', d: ['2024-07-12', '2024-07-12'], ch: ['以太坊类', 'EVM chains'], a: ['未披露', 'Not disclosed'],
    w: ['托管在 Squarespace 的 DeFi 官网域名被劫持，指向盗币页面', 'DeFi website domains hosted at Squarespace were hijacked and pointed to draining pages'],
    l: ['网址对，也可能被劫持', 'Even the right web address can be hijacked'],
    s: [['BleepingComputer', 'https://www.bleepingcomputer.com/news/security/dns-hijacks-target-crypto-platforms-registered-with-squarespace/']] },
  { c: 'site', d: ['2024-10', '2024-10'], ch: ['未注明', 'Not stated'], a: ['未披露', 'Not disclosed'],
    w: ['冒充 WLFI 的 X 账号把人引到假「空投」网站', 'X accounts impersonating WLFI lured people to a fake "airdrop" site'],
    l: ['带「airdrop」「加倍」字样的网站基本是钓鱼', 'Sites promising an "airdrop" or "double your coins" are almost always phishing'],
    s: [['crypto.news', 'https://crypto.news/crypto-phishing-scammers-target-investors-chasing-trump-backed-wlfi-tokens/']] },
  { c: 'site', d: ['2025-02（报道）', '2025-02 (reported)'], ch: ['交易所账户', 'Exchange accounts'], a: ['两个月约 6,500 万美元', 'about $65M in two months'],
    w: ['冒充 Coinbase 官方（假邮件带假工单号）+ 几乎 1:1 克隆的网站', 'Impostors posed as Coinbase (fake emails with fake ticket numbers) plus an almost 1:1 cloned website'],
    l: ['真官方永远不会让你把币转到「安全地址」', 'The real company will never ask you to move coins to a "safe address"'],
    s: [['CoinDesk', 'https://www.coindesk.com/markets/2025/02/04/coinbase-users-are-losing-usd300m-a-year-to-social-scams-zachxbt-says']] },
  { c: 'site', d: ['2025-06-20', '2025-06-20'], ch: ['多链', 'Multi-chain'], a: ['约 4.3 万美元', 'about $43K'],
    w: ['CoinMarketCap 首页被注入脚本，弹出假的「验证钱包」', 'A script injected into CoinMarketCap\'s homepage popped up a fake "verify wallet" prompt'],
    l: ['大网站突然弹「验证钱包」也别连', 'Do not connect, even when a big site suddenly asks you to "verify your wallet"'],
    s: [['Infosecurity', 'https://www.infosecurity-magazine.com/news/web3-wallet-prompt-steals-43000/']] },
  { c: 'site', d: ['2026-01（报道）', '2026-01 (reported)'], ch: ['以太坊类', 'EVM chains'], a: ['未披露', 'Not disclosed'],
    w: ['「mertamask」这类仿冒域名做成 MetaMask 的「双重验证」页，要你输入助记词', 'Look-alike domains such as "mertamask" posed as a MetaMask "two-factor" page asking for your recovery phrase'],
    l: ['要你输助记词的页面都是钓鱼', 'Any page that asks for your recovery phrase is phishing'],
    s: [['Cryptonews', 'https://cryptonews.com/news/slowmist-warns-of-sophisticated-2fa-scam-targeting-metamask-wallets/']] },
  { c: 'site', d: ['2026-03-13～30', '2026-03-13 to 30'], ch: ['多链', 'Multi-chain'], a: ['约 127 万美元', 'about $1.27M'],
    w: ['Google 搜索广告冒充 Uniswap、Morpho、Hyperliquid、Ledger', 'Google search ads impersonated Uniswap, Morpho, Hyperliquid and Ledger'],
    l: ['搜索结果最上面「赞助」的链接别点，官网用书签打开', 'Skip the "sponsored" links at the top of search results; open official sites from your bookmarks'],
    s: [['Cybersecurity News', 'https://cybersecuritynews.com/malicious-google-ads-target-crypto-users/']] },
  { c: 'site', d: ['2026-05（报道）', '2026-05 (reported)'], ch: ['以太坊', 'Ethereum'], a: ['至少 40 万美元', 'at least $400K'],
    w: ['Google 赞助广告排在真 Uniswap 上面，仿站骗无限授权', 'A sponsored Google ad ranked above the real Uniswap, and the clone tricked people into unlimited approvals'],
    l: ['排第一的搜索结果，可能是花钱买的假网站', 'The first search result may be a paid-for fake'],
    s: [['crypto.news', 'https://crypto.news/uniswap-phishing-campaign-on-google-ads-nets-attackers-over-400k/']] },
  { c: 'site', d: ['2026-08-13', '2026-08-13'], ch: ['未注明', 'Not stated'], a: ['约 55 万 USDC', 'about 550,000 USDC'],
    w: ['点了 Google 广告里的假 Hyperliquid，分三笔被转走', 'Someone clicked a fake Hyperliquid in a Google ad; the funds left in three transfers'],
    l: ['交易所入口只用书签', 'Open exchanges only from your bookmarks'],
    s: [['crypto.news', 'https://crypto.news/fake-hyperliquid-google-ad-linked-to-inferno-drainer-steals-usdc/']] },
  { c: 'site', d: ['至今', 'Ongoing'], ch: ['波场', 'TRON'], a: ['—', '—'],
    w: ['MetaMask 钓鱼黑名单里有 25 个冒充 Tronscan 的网址（09-27 下载名单数的）：0 代替 o、换后缀、加前缀、拼错', 'MetaMask\'s phishing blocklist holds 25 addresses impersonating Tronscan (counted in the list downloaded on 2026-09-27): 0 for o, different endings, extra prefixes, misspellings'],
    l: ['看网址要一个字一个字看', 'Read web addresses character by character'],
    s: [['MetaMask 名单 / MetaMask list', 'https://github.com/MetaMask/eth-phishing-detect']] },
  { c: 'site', d: ['至今', 'Ongoing'], ch: ['—', '—'], a: ['—', '—'],
    w: ['ScamSniffer 名单里有 0x00000.icu、0x000000000000000.icu 这种「一串零 + 换后缀」的网址', 'ScamSniffer\'s list includes addresses such as 0x00000.icu and 0x000000000000000.icu - "a row of zeros + a different ending"'],
    l: ['我们的网址只有一个：0x 后面 9 个 0', 'We have only one web address: nine zeros after 0x'],
    s: [['ScamSniffer 名单 / ScamSniffer list', 'https://github.com/scamsniffer/scam-database']] },

  { c: 'scale', d: ['2022-07～2024-06', '2022-07 to 2024-06'], ch: ['以太坊 + BSC', 'Ethereum + BSC'], a: ['2.7 亿次、1,700 万个目标、至少 8,380 万美元', '270 million attempts, 17 million targets, at least $83.8M'],
    w: ['学术论文统计的地址投毒', 'Address poisoning measured in an academic paper'],
    l: ['投毒是撒大网', 'Poisoning is a wide net'],
    s: [['USENIX Security 2025 (arXiv)', 'https://arxiv.org/abs/2501.16681']] },
  { c: 'scale', d: ['截至 2023-10', 'up to 2023-10'], ch: ['波场', 'TRON'], a: ['超过 4.51 亿 USDT', 'more than 451 million USDT'],
    w: ['Bitrace：波场上「0 元转账」类钓鱼的累计损失', 'Bitrace: cumulative losses from "zero-value transfer" phishing on TRON'],
    l: ['波场 USDT 是重灾区', 'TRON USDT is hit hardest'],
    s: [['CryptoPotato', 'https://cryptopotato.com/zero-transfer-phishing-losses-surge-to-451m-usdt-on-tron-network-data/']] },
  { c: 'scale', d: ['2024-02～05（66 天）', '2024-02 to 05 (66 days)'], ch: ['以太坊', 'Ethereum'], a: ['82,031 个假地址', '82,031 fake addresses'],
    w: ['Chainalysis 拆解一个投毒团伙，只有 0.03% 收到超过 100 美元', 'Chainalysis took apart one poisoning gang: only 0.03% of its addresses received more than $100'],
    l: ['低成本撒网，一条鱼上钩就回本', 'A cheap wide net pays off with a single catch'],
    s: [['Chainalysis', 'https://www.chainalysis.com/blog/address-poisoning-scam/']] },
  { c: 'scale', d: ['2024 全年', 'Full year 2024'], ch: ['多链', 'Multi-chain'], a: ['4.94 亿美元', '$494M'],
    w: ['ScamSniffer：签名钓鱼盗币', 'ScamSniffer: coins stolen through signature phishing'],
    l: ['别乱签名', 'Do not sign what you do not understand'],
    s: [['ScamSniffer', 'https://drops.scamsniffer.io/scam-sniffer-2024-web3-phishing-attacks-wallet-drainers-drain-494-million/']] },
  { c: 'scale', d: ['2024 全年', 'Full year 2024'], ch: ['多链', 'Multi-chain'], a: ['钓鱼超过 10 亿美元', 'phishing: more than $1B'],
    w: ['CertiK：钓鱼是 2024 年损失最大的一类', 'CertiK: phishing was the costliest category of 2024'],
    l: ['骗你自己动手，比黑系统更赚钱', 'Tricking you into doing it yourself pays better than hacking systems'],
    s: [['Cointelegraph', 'https://cointelegraph.com/news/phishing-scams-top-crypto-threat-2024-certik']] },
  { c: 'scale', d: ['2025-01 起', 'Since 2025-01'], ch: ['多链', 'Multi-chain'], a: ['6,540 万笔', '65.4 million transactions'],
    w: ['Blockaid 标记的投毒交易；2026 年 1 月一个月就有 340 万次', 'Poisoning transactions flagged by Blockaid; 3.4 million in January 2026 alone'],
    l: ['每天都在发生', 'It happens every day'],
    s: [['Blockaid', 'https://blockaid.io/blog/address-poisoning-the-growing-threat-draining-millions-from-crypto-users']] },
  { c: 'scale', d: ['2025 全年', 'Full year 2025'], ch: ['多链', 'Multi-chain'], a: ['8,385 万美元', '$83.85M'],
    w: ['ScamSniffer：签名钓鱼降了 83%，但仍有 11 起单笔超 100 万美元', 'ScamSniffer: signature phishing fell 83%, yet 11 single losses still exceeded $1M'],
    l: ['总量降了，大户照样被一次打穿', 'Totals fell, but big holders still get wiped out in one go'],
    s: [['ScamSniffer', 'https://drops.scamsniffer.io/scam-sniffer-2025-crypto-phishing-losses-fall-83-to-84-million/']] },
  { c: 'scale', d: ['2025 全年', 'Full year 2025'], ch: ['多链', 'Multi-chain'], a: ['33.5 亿美元', '$3.35B'],
    w: ['CertiK：总损失；钓鱼 7.23 亿美元排第二', 'CertiK: total losses; phishing came second at $723M'],
    l: ['钓鱼年年排前两名', 'Phishing ranks in the top two every year'],
    s: [['CertiK', 'https://www.certik.com/blog/hack3d-the-web3-security-report-2025']] },
  { c: 'scale', d: ['2025 全年', 'Full year 2025'], ch: ['多链', 'Multi-chain'], a: ['钓鱼约 1.77 亿、私钥泄露约 1.80 亿美元', 'phishing about $177M, leaked private keys about $180M'],
    w: ['Beosin 年报', 'Beosin annual report'],
    l: ['私钥一旦泄露，损失跟被钓鱼一样大', 'A leaked private key costs as much as being phished'],
    s: [['Beosin', 'https://www.beosin.com/resources/2025%E5%B9%B4Web3%E5%8C%BA%E5%9D%97%E9%93%BE%E5%AE%89%E5%85%A8%E6%80%81%E5%8A%BF%E5%B9%B4%E6%8A%A5.pdf']] },
  { c: 'scale', d: ['2025 全年', 'Full year 2025'], ch: ['多链', 'Multi-chain'], a: ['约 7.13 亿美元', 'about $713M'],
    w: ['Chainalysis：个人钱包被盗；以太坊和波场被盗率最高', 'Chainalysis: thefts from personal wallets; Ethereum and TRON had the highest theft rates'],
    l: ['波场用户是被盗高发人群', 'TRON users are among the most often robbed'],
    s: [['Chainalysis', 'https://www.chainalysis.com/blog/crypto-hacking-stolen-funds-2026/']] },
  { c: 'scale', d: ['2025 全年', 'Full year 2025'], ch: ['多链', 'Multi-chain'], a: ['约 170 亿美元', 'about $17B'],
    w: ['Chainalysis：诈骗收入；冒充类诈骗同比涨 1,400%', 'Chainalysis: scam revenue; impersonation scams grew 1,400% year on year'],
    l: ['冒充官方是涨得最快的骗法', 'Impersonating officials is the fastest-growing scam'],
    s: [['Chainalysis', 'https://www.chainalysis.com/blog/crypto-scams-2026/']] },
  { c: 'scale', d: ['2026-03（报道）', '2026-03 (reported)'], ch: ['以太坊', 'Ethereum'], a: ['+612%', '+612%'],
    w: ['Etherscan：手续费降低后，USDT 粉尘转账从约 420 万笔涨到约 2,990 万笔', 'Etherscan: after fees dropped, USDT dust transfers rose from about 4.2 million to about 29.9 million'],
    l: ['转账越便宜，投毒越多', 'The cheaper transfers get, the more poisoning there is'],
    s: [['FXStreet', 'https://www.fxstreet.com/cryptocurrencies/news/etherscan-warns-of-surge-in-address-poisoning-scams-on-ethereum-after-fusaka-upgrade-202603130124']] },
  { c: 'scale', d: ['2026 上半年', 'First half of 2026'], ch: ['多链', 'Multi-chain'], a: ['13.16 亿美元', '$1.316B'],
    w: ['CertiK：钱包被攻破成了损失最大的一类', 'CertiK: wallet compromises became the costliest category'],
    l: ['损失越来越集中在大户身上', 'Losses concentrate more and more on big holders'],
    s: [['CertiK', 'https://www.certik.com/skynet-report/certik-hack3d-h1-2026-report']] },
  { c: 'scale', d: ['2026 上半年', 'First half of 2026'], ch: ['波场等', 'TRON and others'], a: ['欺诈类高风险地址收款超过 160 亿 USDT', 'high-risk fraud addresses received more than 16 billion USDT'],
    w: ['Bitrace：被冻结的代币里 95% 是波场 USDT', 'Bitrace: 95% of frozen tokens were TRON USDT'],
    l: ['波场 USDT 是黑灰产的主通道', 'TRON USDT is the main channel for illicit money'],
    s: [['吴说（Bitrace 报告）/ Wu Blockchain (Bitrace report)', 'https://www.wublock123.com/articles/bitrace-2026-h1-crypto-crime-report-59510']] },
];
var NEWS_CAT = { poison: ['地址投毒', 'Address poisoning'], key: ['私钥', 'Private keys'], fake: ['假币 / 假合约', 'Fake tokens'], site: ['假网址 / 冒充官方', 'Fake sites & impersonation'], scale: ['整体规模', 'The big picture'] };
